services:
#Database configuration
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    #Environment variables for database setup
    environment:
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
      POSTGRES_DB: ${PGSQL_DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    #Database port
    ports:
      - "${DB_PORT}:5432"
    #Health check configuration to ensure the database is running  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGSQL_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    
    #Attach the service to a custom network
    networks:
      - studentsmarthomenet
  server:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_NAME: ${DB_NAME}
      SERVER_PORT: ${APP_SERVER_PORT}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${APP_SERVER_PORT}:8000"
    networks:
      - studentsmarthomenet

volumes:
  db_data:
networks:
  studentsmarthomenet:
    driver: bridge
