services:

  # postgresql service
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
      POSTGRES_DB: ${PGSQL_DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      # expose default postgresql port
      - "${DB_PORT}:5432"
    healthcheck:
      # verify if postgresql is ready
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      # connect container to 'ssh-network'
      - ssh-network

  # app server
  server:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_NAME: ${DB_NAME}
      SERVER_PORT: ${APP_SERVER_PORT}
    depends_on:
      # ensure 'db' service is healthy
      db:
        condition: service_healthy
    ports:
      # expose server's port to host
      - "${APP_SERVER_PORT}:8000"
    networks:
      # connect container to 'ssh-network'
      - ssh-network

# define named volumes
volumes:
  db_data:
